module Turbo
  # Resolves a 'partial' generated by Turbo::PartialExtractor from Rails.cache
  # instead of the filesystem.
  #
  # Registered via append_view_path so it's only
  # consulted after the normal FileSystemResolver finds nothing
  class CachedPartialResolver < ActionView::Resolver
    def find_templates(name, prefix, partial, details, locals = [])
      path = ActionView::TemplatePath.build(name, prefix, partial)
      source = Rails.cache.read(PartialExtractor.cache_key("#{prefix}/#{name}".delete_prefix("/")))
      return [] unless source

      [ActionView::Template.new(
        source,
        "generated by Turbo::CachedPartialResolver: #{path.virtual}",
        ActionView::Template::Handlers::ERB,
        virtual_path: path.virtual,
        format: :html,
        variant: nil,
        locals: locals
      )]
    end
  end
end
