name: Request Review
on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  request_review:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Request reviews
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const reviewers = ['seanpdoyle', 'jorgemanrubia'];
            github.rest.pulls.requestReviewers({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
              reviewers: reviewers
            });
